version: 2.1

jobs:
  build_and_test:
    docker:
     - image: nimlang/nim
    steps:
      - checkout
      - run: |
          cd nim-brainfuck-interpreter
          nimble build -y
          nimble test -y

workflows:
  build_and_test:
    jobs:
      - build_and_test